# ==============================================
# QuantTrader Configuration Example
# ==============================================
# Copy this file to config.toml and update the values
# ==============================================

[app]
name = "同花顺交易自动化"
version = "1.0.0"
#自己训练的验证码识别模型目录，目录下必须有captcha_ocr.onnx和captcha_ocr.onnx.data
onnx_model_dir = ""
# 是否保存识别错误的验证码图片，图片保存在 C:\Users\你的用户名\easyths\captcha_error\目录下，收集好之后，重命名为：{验证码}_{uuid}.png, 发送到邮箱noimank@163.com
# 收集的数据将对改进验证码模型非常有帮助，欢迎大家上传数据集！
# 不参与改进请修改为false
save_error_captcha_image = true

[trading]
app_path = "C:/同花顺远航版/transaction/xiadan.exe"

[queue]
max_size = 1000
priority_levels = 5
batch_size = 10

[api]
host = "0.0.0.0"
port = 7648
# MCP服务器传输类型: http, streamable-http, sse
mcp_server_type = "streamable-http"
rate_limit = 100
# CORS允许的源 - *表示允许所有，逗号分隔多个源
cors_origins = "*"
# API密钥 - 可以不设置，设置之后所有API请求都需要在Header中提供: Authorization: Bearer <api_key>
key = ""
# IP白名单 - 留空表示允许所有IP，逗号分隔多个IP，支持通配符*,如: 127.0.0.1,192.168.1.*
ip_whitelist = ""

[logging]
level = "INFO"
#默认在："C:/Users/你的用户名/easyths/log.txt"
file = ""
